### ISSUE TITLE
Cannot build http-logger-parent

### ISSUE THREAD

**Issue by shalugin** [lesinsa/horn-soft-pub#1]
When I execute 

> mvn package

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.horn:http-logger-parent:[unknown-version] (D:\temp\github\horn-soft-pub\http-logger\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.horn:jee-parent:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException`

```
    <parent>
        <artifactId>jee-parent</artifactId>
        <groupId>com.horn</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

```

**Comment by lesinsa** [comment]
fixed
